# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0005_auto_20160224_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('expire_date', models.DateTimeField()),
                ('key', models.CharField(db_index=True, max_length=40, verbose_name='computer key')),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
